title:             Blockchain development tips
#email:             your-email@example.com
description:       My blog about blockchain development. Hyperledger Fabric, solidity, ...
author:            José Luis Cánovas Sánchez
baseurl:           "/"
url:               "https://jlcs-es.github.io/blockchainblog"

# Social Profiles
twitter_username:  jlcs_es
github_username:   jlcs-es
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          7
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
